Repository the-pool/the-pool-api, pull requests merged in 2023-05, with the labels that each got.

#174 increase action 을 inteceptor 가 아닌 emitter 로 수행합니다.
  package-lock.json
  package.json
  src/app.module.ts
  src/constants/constant.ts
  src/decorators/increase-member-follow-set-metadata.interceptor.decorator.ts
  src/decorators/increase-member-statistics-set-metadata.interceptor-decorator.ts
  src/interceptors/increase-member-follow.interceptor.ts
  src/interceptors/increase-member-statistics.interceptor.ts
  src/modules/comment/services/comment.service.spec.ts
  src/modules/comment/services/comment.service.ts
  src/modules/lesson/controllers/lesson-comment.controller.spec.ts
  src/modules/lesson/controllers/lesson-comment.controller.ts
  src/modules/lesson/controllers/lesson.controller.spec.ts
  src/modules/lesson/controllers/lesson.controller.ts
  src/modules/lesson/lesson.module.ts
  src/modules/lesson/services/lesson.service.spec.ts
  src/modules/lesson/services/lesson.service.ts
  src/modules/member-friendship/controllers/member-friendship.controller.spec.ts
  src/modules/member-friendship/controllers/member-friendship.controller.ts
  src/modules/member-friendship/controllers/member-friendship.swagger.ts
  src/modules/member-friendship/dtos/delete-member-following-request-param.dto.ts
  src/modules/member-friendship/events/member-friendships.event.spec.ts
  src/modules/member-friendship/events/member-friendships.event.ts
  src/modules/member-friendship/listeners/member-friendships.listeners.spec.ts
  src/modules/member-friendship/listeners/member-friendships.listeners.ts
  src/modules/member-friendship/member-friendship.module.ts
  src/modules/member-friendship/services/member-friendship.service.spec.ts
  src/modules/member-friendship/services/member-friendship.service.ts
  src/modules/member-statistics/events/member-statistics.event.spec.ts
  src/modules/member-statistics/events/member-statistics.event.ts
  src/modules/member-statistics/listeners/member-statistics.listeners.spec.ts
  src/modules/member-statistics/listeners/member-statistics.listeners.ts
  src/modules/member-statistics/member-statistics.module.ts
  src/modules/member-statistics/types/member-statistics.type.ts
  src/modules/solution/controllers/solution-comment.controller.spec.ts
  src/modules/solution/controllers/solution-comment.controller.ts
  src/modules/solution/controllers/solution.controller.spec.ts
  src/modules/solution/controllers/solution.controller.swagger.ts
  src/modules/solution/controllers/solution.controller.ts
  src/modules/solution/services/solution.service.spec.ts
  src/modules/solution/services/solution.service.ts
  src/modules/solution/solution.module.ts
  test/mock/mock-event.ts
  test/mock/mock-libs.ts
Labels: Feature

#180 풀이 목록 조회에 좋아요한 풀이 필터링 추가
  src/modules/solution/controllers/solution.controller.spec.ts
  src/modules/solution/controllers/solution.controller.ts
  src/modules/solution/dtos/read-many-solution-request-query.dto.ts
  src/modules/solution/services/solution.service.spec.ts
  src/modules/solution/services/solution.service.ts
Labels: Feature

#181 과제 목록조회 확장
  src/modules/lesson/constants/lesson.const.ts
  src/modules/lesson/controllers/lesson.controller.spec.ts
  src/modules/lesson/controllers/lesson.controller.ts
  src/modules/lesson/dtos/lesson/read-many-lesson-query.dto.ts
  src/modules/lesson/services/lesson.service.spec.ts
  src/modules/lesson/services/lesson.service.ts
Labels: Feature

#179 event-emitter를 통해서 조회수 증가되도록 수정
  src/app.module.ts
  src/modules/lesson/controllers/lesson.controller.spec.ts
  src/modules/lesson/controllers/lesson.controller.ts
  src/modules/lesson/dtos/lesson/read-one-lesson.dto.ts
  src/modules/lesson/events/lesson-hit.event.ts
  src/modules/lesson/lesson.module.ts
  src/modules/lesson/listeners/lesson-hit.listener.spec.ts
  src/modules/lesson/listeners/lesson-hit.listener.ts
  src/modules/lesson/services/lesson.service.spec.ts
  src/modules/lesson/services/lesson.service.ts
  src/modules/member/services/member.service.spec.ts
  test/mock/mock-services.ts
Labels: Feature

#176 configService 를 custom 합니다.
  .github/workflows/deploy.yml
  src/app.module.ts
  src/main.ts
  src/middlewares/use-development.middleware.ts
  src/modules/core/auth/auth.module.ts
  src/modules/core/auth/helpers/auth.helper.spec.ts
  src/modules/core/auth/helpers/auth.helper.ts
  src/modules/core/auth/jwt/jwt.strategy.ts
  src/modules/core/auth/jwt/optional-jwt.strategy.spec.ts
  src/modules/core/auth/jwt/optional-jwt.strategy.ts
  src/modules/core/core.module.ts
  src/modules/core/notification/notification.module.ts
  src/modules/core/notification/services/notification.service.spec.ts
  src/modules/core/notification/services/notification.service.ts
  src/modules/core/notification/type/notification.type.ts
  src/modules/core/private-storage/services/aws-s3-storage.service.spec.ts
  src/modules/core/private-storage/services/aws-s3-storage.service.ts
  src/modules/core/the-pool-config/constants/the-pool-config.constant.ts
  src/modules/core/the-pool-config/services/the-pool-config.service.spec.ts
  src/modules/core/the-pool-config/services/the-pool-config.service.ts
  src/modules/core/the-pool-config/the-pool-config.module.ts
  src/modules/member-social-link/services/member-social-link.service.spec.ts
  src/modules/member-social-link/services/member-social-link.service.ts
  src/modules/member/controllers/member.controller.spec.ts
  test/mock/mock-services.ts
  test/utils/setTestingApp.ts
Labels: Feature

#183 project 문서
  README.md
  package.json
Labels: Doc

#187 Feature/186 - lesson solution 좋아요
  package-lock.json
  src/constants/enum.ts
  src/modules/core/database/prisma/prisma.service.ts
  src/modules/solution/controllers/solution.controller.spec.ts
  src/modules/solution/controllers/solution.controller.swagger.ts
  src/modules/solution/controllers/solution.controller.ts
  src/modules/solution/entities/solution-default.entity.ts
  src/modules/solution/services/solution.service.spec.ts
  src/modules/solution/services/solution.service.ts
  test/mock/mock-services.ts
Labels: Feature

#189 🐛 solution 내 title 추가, api doc 수정
  prisma/schema.prisma
  src/constants/constant.ts
  src/modules/solution/dtos/create-solution-request-body.dto.ts
  src/modules/solution/dtos/read-many-solution-request-query.dto.ts
  src/modules/solution/entities/solution.entity.ts
Labels: Bugfix

#191 과제 리스트 풀이 리스트 수정
  src/modules/lesson/controllers/lesson.controller.spec.ts
  src/modules/lesson/controllers/lesson.controller.ts
  src/modules/lesson/dtos/lesson/read-many-lesson-query.dto.ts
  src/modules/lesson/services/lesson.service.spec.ts
  src/modules/lesson/services/lesson.service.ts
  src/modules/solution/controllers/solution.controller.spec.ts
  src/modules/solution/controllers/solution.controller.ts
  src/modules/solution/dtos/read-many-solution-request-query.dto.ts
  src/modules/solution/services/solution.service.spec.ts
  src/modules/solution/services/solution.service.ts
Labels: Bugfix
