Repository the-pool/the-pool-api, pull requests merged in 2023-03, with the labels that each got.

#117 Feature/113: 과제 좋아요 생성 및 삭제 api 입니다
  prisma/schema.prisma
  src/constants/enum.ts
  src/modules/core/database/prisma/prisma.service.ts
  src/modules/lesson/controllers/lesson-like.controller.spec.ts
  src/modules/lesson/controllers/lesson-like.controller.ts
  src/modules/lesson/entities/lesson-like.entity.ts
  src/modules/lesson/lesson.module.ts
  src/modules/lesson/services/lesson-like.service.spec.ts
  src/modules/lesson/services/lesson-like.service.ts
  src/modules/lesson/swaggers/lesson-like.swagger.ts
  test/mock/mock-services.ts
Labels: Feature

#121 Feature/120: deploy.yml 환경변수 추가
  .github/workflows/deploy.yml
Labels: Bugfix, Config

#119 Feature/110: webhook 을 이용한 알림 기능
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/filters/http-nest-Internal-server-error-exception.filter.ts
  src/filters/http-node-internal-server-error-exception.filter.ts
  src/interceptors/increase-member-follow.interceptor.ts
  src/interceptors/increase-member-statistics.interceptor.ts
  src/main.ts
  src/modules/core/core.module.ts
  src/modules/core/notification/constants/notification.constant.ts
  src/modules/core/notification/notification.module.ts
  src/modules/core/notification/services/notification.service.spec.ts
  src/modules/core/notification/services/notification.service.ts
  src/modules/core/notification/type/notification.type.ts
  src/modules/member-friendship/controllers/member-friendship.controller.spec.ts
  src/modules/member-friendship/member-friendship.module.ts
  src/modules/test/mock-dto.ts
  src/modules/test/mock-prisma.ts
  test/mock/mock-libs.ts
  test/mock/mock-services.ts
  test/utills/set-testing-app.ts
  test/utils/setTestingApp.ts
Labels: Feature

#125 Feature/123: member 의 social 링크 리스트 조회 api
  .github/workflows/deploy.yml
  prisma/functions/member-social-link.seed.ts
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/modules/index.ts
  src/modules/member-social-link/controllers/member-social-link.controller.spec.ts
  src/modules/member-social-link/controllers/member-social-link.controller.ts
  src/modules/member-social-link/controllers/member-social-link.swagger.ts
  src/modules/member-social-link/entities/member-social-link.entity.ts
  src/modules/member-social-link/member-social-link.module.ts
  src/modules/member-social-link/services/member-social-link.service.spec.ts
  src/modules/member-social-link/services/member-social-link.service.ts
  test/mock/mock-services.ts
Labels: Feature, DB

#126 Feature/118 과제 댓글 생성 api
  src/common/common.ts
  src/constants/enum.ts
  src/interceptors/increase-member-statistics.interceptor.ts
  src/main.ts
  src/modules/comment/dtos/create-comment.dto.ts
  src/modules/comment/entities/comment.entity.ts
  src/modules/comment/services/comment.service.spec.ts
  src/modules/comment/services/comment.service.ts
  src/modules/lesson/controllers/lesson-comment.controller.spec.ts
  src/modules/lesson/controllers/lesson-comment.controller.ts
  src/modules/lesson/dtos/hashtag/lesson-hashtag-param.dto.ts
  src/modules/lesson/entities/lesson-comment.entity.ts
  src/modules/lesson/lesson.module.ts
  src/modules/lesson/swaggers/lesson-comment.swagger.ts
  src/modules/solution/solution.module.ts
  src/types/type.ts
  test/mock/mock-services.ts
Labels: Feature

#133 과제 댓글 삭제 api 입니다
  src/modules/comment/services/comment.service.spec.ts
  src/modules/comment/services/comment.service.ts
  src/modules/lesson/controllers/lesson-comment.controller.spec.ts
  src/modules/lesson/controllers/lesson-comment.controller.ts
  src/modules/lesson/dtos/comment/lesson-comment-param.dto.ts
  src/modules/lesson/swaggers/lesson-comment.swagger.ts
  test/mock/mock-services.ts
Labels: Feature

#138 과제 댓글 수정 api
  src/modules/comment/dtos/create-comment-base.dto.ts
  src/modules/comment/dtos/update-comment-base.dto.ts
  src/modules/comment/services/comment.service.spec.ts
  src/modules/comment/services/comment.service.ts
  src/modules/lesson/controllers/lesson-comment.controller.spec.ts
  src/modules/lesson/controllers/lesson-comment.controller.ts
  src/modules/lesson/swaggers/lesson-comment.swagger.ts
  src/types/type.ts
  test/mock/mock-services.ts
Labels: Feature

#139 과제 상세조회 api prisma raw query > prisma built-in method 변경 및 LessonRepository 제거
  src/modules/lesson/controllers/lesson.controller.ts
  src/modules/lesson/dtos/lesson/read-one-lesson.dto.ts
  src/modules/lesson/entities/lesson-level.entity.ts
  src/modules/lesson/lesson.module.ts
  src/modules/lesson/repositories/lesson.repository.ts
  src/modules/lesson/services/lesson.service.spec.ts
  src/modules/lesson/services/lesson.service.ts
  test/mock/mock-repositories.ts
Labels: Feature

#142 Feature/140
  prisma/schema.prisma
  src/constants/enum.ts
  src/modules/comment/services/comment.service.ts
  src/modules/solution/controllers/solution-comment.controller.spec.ts
  src/modules/solution/controllers/solution-comment.controller.ts
  src/modules/solution/controllers/solution-comment.swagger.ts
  src/modules/solution/entities/solution-comment.entity.ts
  src/modules/solution/solution.module.ts
  src/types/type.ts
Labels: Feature

#143 :sparkles: #141 - 과제 상세조회시 조회수 증가 로직 추가
  src/modules/lesson/controllers/lesson.controller.spec.ts
  src/modules/lesson/controllers/lesson.controller.ts
  src/modules/lesson/services/lesson.service.spec.ts
  src/modules/lesson/services/lesson.service.ts
  test/mock/mock-services.ts
Labels: Feature

#147 notification module 로 인해 깨지는 테스트코드 수정
  src/modules/solution/controllers/solution.controller.spec.ts
  test/mock/mock-libs.ts
Labels: Feature
