Repository the-pool/the-pool-api, pull requests merged in 2023-02, with the labels that each got.

#82 Feature/78
  src/decorators/increase-member-statistics-set-metadata.guard-decorator.ts
  src/decorators/member-major-set-metadata.guard-decorator.spec.ts
  src/decorators/member-major-set-metadata.guard-decorator.ts
  src/decorators/member-statuses-set-metadata.guard-decorator.spec.ts
  src/decorators/member-statuses-set-metadata.guard-decorator.ts
  src/decorators/own-member-set-metadata.guard-decorator.spec.ts
  src/decorators/own-member-set-metadata.guard-decorator.ts
  src/decorators/set-response-set-metadata.interceptor-decorator.ts
  src/guards/member-major.guard.spec.ts
  src/guards/member-major.guard.ts
  src/guards/member-status.guard.spec.ts
  src/guards/member-status.guard.ts
  src/guards/own-member.guard.spec.ts
  src/guards/own-member.guard.ts
  src/helpers/example.helper.ts
  src/interceptors/increase-member-statistics.interceptor.ts
  src/interceptors/set-response.interceptor.ts
  src/modules/major/entities/major.entity.ts
  src/modules/major/entities/major.entity.v2.ts
  src/modules/member-interest/controllers/member-interest.controller.ts
  src/modules/member-skill/controllers/member-skill.controller.ts
  src/modules/member-statistics/controllers/member-statistics.controller.ts
  src/modules/member/constants/member.const.ts
  src/modules/member/controllers/member.controller.spec.ts
  src/modules/member/controllers/member.controller.ts
  src/modules/member/controllers/member.swagger.ts
  src/modules/member/dtos/create-member-major-mapping-request-param.dto.ts
  src/modules/member/services/member.service.spec.ts
  src/modules/member/services/member.service.ts
  src/modules/member/types/member.type.ts
  test/mock/mock-libs.ts
  test/mock/mock-services.ts
  test/mock/mock.type.ts
Labels: Feature

#95 :bug: #93 - member statistics 리스트 조회 시 기본 order memberId 로 변경
  src/modules/member-statistics/dtos/find-member-statistics-list-query.dto.ts
Labels: Bugfix

#92 Feature/79: member 와 majorSKill 을 다중 매핑하는 api
  prisma/schema.prisma
  src/common/common.spec.ts
  src/common/common.ts
  src/constants/enum.ts
  src/dtos/id-request-param.dto.ts
  src/modules/member/controllers/member.controller.spec.ts
  src/modules/member/controllers/member.controller.ts
  src/modules/member/controllers/member.swagger.ts
  src/modules/member/dtos/create-member-major-skill-mapping-request-param.dto.ts
  src/modules/member/entities/member-major-mapping.entity.ts
  src/modules/member/services/member.service.spec.ts
  src/modules/member/services/member.service.ts
  src/types/type.ts
  test/mock/mock-services.ts
Labels: Feature

#97 Feature/96
  src/common/common.ts
  src/helpers/common.helper.spec.ts
  src/helpers/common.helper.ts
  src/modules/core/auth/auth.module.ts
  src/modules/core/auth/helpers/auth.helper.spec.ts
  src/modules/core/auth/helpers/auth.helper.ts
  src/modules/core/auth/services/auth.service.spec.ts
  src/modules/core/auth/services/auth.service.ts
  src/modules/core/auth/type/auth.type.ts
  src/modules/member/constants/member.const.ts
  src/modules/member/constants/member.enum.ts
  src/modules/member/dtos/login-or-sign-up-request-body.dto.ts
  src/modules/member/entities/member.entity.ts
  test/mock/mock-helpers.ts
Labels: Feature

#101 Feature/100: member 와 memberSkill 다중 매핑 제거 api
  src/modules/member/controllers/member.controller.spec.ts
  src/modules/member/controllers/member.controller.ts
  src/modules/member/controllers/member.swagger.ts
  src/modules/member/dtos/delete-member-skills-mapping-request-param.dto.ts
  src/modules/member/services/member.service.spec.ts
  src/modules/member/services/member.service.ts
  test/mock/mock-services.ts
Labels: Feature

#103 Feature/102: member 와 memberInterest 다중 매핑 api
  src/constants/enum.ts
  src/modules/member-interest/services/member-interest.service.spec.ts
  src/modules/member-interest/services/member-interest.service.ts
  src/modules/member/controllers/member.controller.spec.ts
  src/modules/member/controllers/member.controller.ts
  src/modules/member/controllers/member.swagger.ts
  src/modules/member/dtos/create-member-interest-mapping.request-param.dto.ts
  src/modules/member/entities/member-interest-mapping.entity.ts
  src/modules/member/services/member.service.spec.ts
  src/modules/member/services/member.service.ts
  test/mock/mock-services.ts
Labels: Feature, Bugfix

#105 Feature/104: member 와 memberInterest 다중 매핑 제거 api
  src/modules/member/controllers/member.controller.spec.ts
  src/modules/member/controllers/member.controller.ts
  src/modules/member/controllers/member.swagger.ts
  src/modules/member/dtos/delete-member-interest-mapping.request-param.dto.ts
  src/modules/member/services/member.service.spec.ts
  src/modules/member/services/member.service.ts
  test/mock/mock-services.ts
Labels: Feature

#107 Feature/106: member follow api
  src/constants/constant.ts
  src/decorators/increase-member-follow-set-metadata.interceptor.decorator.ts
  src/decorators/increase-member-statistics-set-metadata.interceptor-decorator.ts
  src/decorators/other-member-set-metadata.guard-decorator.spec.ts
  src/decorators/other-member-set-metadata.guard-decorator.ts
  src/guards/other-member.guard.spec.ts
  src/guards/other-member.guard.ts
  src/interceptors/increase-member-follow.interceptor.ts
  src/interceptors/increase-member-statistics.interceptor.ts
  src/modules/member-friendship/controllers/member-friendship.controller.spec.ts
  src/modules/member-friendship/controllers/member-friendship.controller.ts
  src/modules/member-friendship/controllers/member-friendship.swagger.ts
  src/modules/member-friendship/dtos/create-member-following-request-param.dto.ts
  src/modules/member-friendship/member-friendship.module.ts
  src/modules/member-friendship/services/member-friendship.service.spec.ts
  src/modules/member-friendship/services/member-friendship.service.ts
  src/modules/member-statistics/types/member-statistics.type.ts
  src/modules/member/constants/member.const.ts
  test/mock/mock-services.ts
Labels: Feature

#112 Feature/111 LessonBookmark create, delete
  prisma/schema.prisma
  src/constants/enum.ts
  src/modules/core/database/prisma/prisma.service.ts
  src/modules/lesson/controllers/lesson-bookmark.controller.spec.ts
  src/modules/lesson/controllers/lesson-bookmark.controller.ts
  src/modules/lesson/entities/lesson-bookmark.entity.ts
  src/modules/lesson/lesson.module.ts
  src/modules/lesson/services/lesson-bookmark.service.spec.ts
  src/modules/lesson/services/lesson-bookmark.service.ts
  src/modules/lesson/swaggers/lesson-bookmark.swagger.ts
  test/mock/mock-services.ts
Labels: Feature

#109 Feature/108: member unfollow api
  prisma/schema.prisma
  src/modules/member-friendship/controllers/member-friendship.controller.spec.ts
  src/modules/member-friendship/controllers/member-friendship.controller.ts
  src/modules/member-friendship/controllers/member-friendship.swagger.ts
  src/modules/member-friendship/dtos/delete-member-following-request-param.dto.ts
  src/modules/member-friendship/services/member-friendship.service.spec.ts
  src/modules/member-friendship/services/member-friendship.service.ts
  test/mock/mock-services.ts
Labels: Feature

#116 Bugfix/115
  src/app.module.ts
  src/modules/core/auth/helpers/auth.helper.spec.ts
  src/modules/core/auth/helpers/auth.helper.ts
  src/modules/member/controllers/member.swagger.ts
  src/modules/member/services/member-validation.service.spec.ts
  src/modules/member/services/member-validation.service.ts
Labels: Bugfix
